//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coink.Microservice.Infrastructure.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coink.Microservice.Infrastructure.Constants.SqlQueries", typeof(SqlQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM sp_department_get_all().
        /// </summary>
        internal static string DepartmentGetAll {
            get {
                return ResourceManager.GetString("DepartmentGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM sp_department_get_by_country_id(@p_country_id).
        /// </summary>
        internal static string DepartmentGetByCountryId {
            get {
                return ResourceManager.GetString("DepartmentGetByCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM sp_department_get_by_id(@p_id).
        /// </summary>
        internal static string DepartmentGetById {
            get {
                return ResourceManager.GetString("DepartmentGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT sp_municipality_exists(@p_id).
        /// </summary>
        internal static string MunicipalityExists {
            get {
                return ResourceManager.GetString("MunicipalityExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM sp_municipality_get_all().
        /// </summary>
        internal static string MunicipalityGetAll {
            get {
                return ResourceManager.GetString("MunicipalityGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM sp_municipality_get_by_department_id(@p_department_id).
        /// </summary>
        internal static string MunicipalityGetByDepartmentId {
            get {
                return ResourceManager.GetString("MunicipalityGetByDepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM sp_municipality_get_by_id(@p_id).
        /// </summary>
        internal static string MunicipalityGetById {
            get {
                return ResourceManager.GetString("MunicipalityGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM sp_user_create(@p_name, @p_phone, @p_address, @p_municipality_id).
        /// </summary>
        internal static string UserCreate {
            get {
                return ResourceManager.GetString("UserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT sp_user_delete(@p_id).
        /// </summary>
        internal static string UserDelete {
            get {
                return ResourceManager.GetString("UserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM sp_user_get_all().
        /// </summary>
        internal static string UserGetAll {
            get {
                return ResourceManager.GetString("UserGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM sp_user_get_by_id(@p_id).
        /// </summary>
        internal static string UserGetById {
            get {
                return ResourceManager.GetString("UserGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM sp_user_update(@p_id, @p_name, @p_phone, @p_address, @p_municipality_id).
        /// </summary>
        internal static string UserUpdate {
            get {
                return ResourceManager.GetString("UserUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM sp_country_get_all().
        /// </summary>
        internal static string CountryGetAll {
            get {
                return ResourceManager.GetString("CountryGetAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM sp_country_get_by_id(@p_id).
        /// </summary>
        internal static string CountryGetById {
            get {
                return ResourceManager.GetString("CountryGetById", resourceCulture);
            }
        }
    }
}
